### ISSUE TITLE
Check for headered ROM?

### ISSUE THREAD

**Issue by gingerbeardman** [marcrobledo/RomPatcher.js#1]
Often a patch requires a specific ROM. Maybe headered, maybe unheadered. 

Eg. Seiken Densetsu 3. 

But your tool doesnt check for headers so it's possible to patch the wrong ROM?

**Comment by frostitution** [comment]
Adding on to this, maybe a way to just say "This patch requires a headered ROM" and during the patching process, add the header, apply the patch, then remove the header all in one swoop (similar to using TUSH)? Or modify the IPS file to strip the header out (similar to ipsbehead).

**Comment by gingerbeardman** [comment]
The IPS patch itself doesn't contain any information about whether the ROM it's meant to patch is headered, or indeed anything about the ROM. 

So I think, similar to the other issue about checksums, the tool would need to use the metadata on the patch page to do these extra checks.

**Comment by marcrobledo** [comment]
I'll take a look at it.
I can add a checkbox to add a temporary header before patching.

**Comment by marcrobledo** [comment]
Fixed in 5ea4024aaf6d32ff7958173e6fcab3e68a4d308b

What it does:
* checks if file is smc, sfc, fig or swc
* a checkbox appears, if checked...
* it creates a fake header
* patches the rom
* removes the fake header

Changes are up, however I'm having problems with the old appcache file and it doesn't seem to show the latest files.

**Comment by marcrobledo** [comment]
Looks like it already loads the newest files.
Can you confirm the new feature works as expected?
