### ISSUE TITLE
Verify checksums

### ISSUE THREAD

**Issue by gingerbeardman** [marcrobledo/RomPatcher.js#2]
Is it possible to check uploaded ROM against required checksum listed on RHDN patch page? 

This way we can avoid more incorrect ROM patching.

**Comment by marcrobledo** [comment]
Yes and no.

RHDN could implement a very simple web API that would return data (available patches, etc) from a crc you send as a parameter.
But due to security reasons, it's impossible to do Ajax requests whose origin domain comes from another source than destination. It could be fixed by enabling [CORS](https://www.html5rocks.com/en/tutorials/cors/) in their server, or by using a server side language (which is impossible in GitHub pages).

Best solution would be to upload the whole RomPatcher.js along implementing the new functions in RHDN server. Indeed, I already talked with a staff member about this. However, this would require a significant overhaul in their database. I wish I could collaborate with them, but I'm really busy right now :-(

**Comment by gingerbeardman** [comment]
I thought as much. I think lots definitely something they should do, because the situation needs to be simplified for the good of everybody.

**Comment by marcrobledo** [comment]
Development and progress for this is discussed in #7
