### ISSUE TITLE
Cannot generate .ips files for Switch due to file size limit

### ISSUE THREAD

**Issue by tech-ticks** [marcrobledo/RomPatcher.js#21]
Since this tool doesn't allow generating .ips patches over 16 megabytes, it's impossible to create patches for Switch mods of some games. I've bypassed the limit in my local copy to generate a patch for a 35 MB binary which worked fine, so it seems like this limit could be removed without any problems.

**Comment by btimofeev** [comment]
@tech-ticks the patch cannot handle files larger than 16 megabytes in accordance with the IPS specification. Your IPS patch will not be compatible with all other patchers if you change this. It is very bad to do this, since it will be a big problem for users to find a patcher that supports a specific version of the patch. It's better to focus on standards and choose the patch format that suits you best. You need to use UPS or BPS formats for large files. 

There is also the IPS32 format (most likely this is what your implementation looks like), but such patches are not at all common. This is the same IPS, but it has MAGIC = "IPS32", 4-byte offsets and the end-of-file "EEOF" instead of "EOF".
