### ISSUE TITLE
Only Allow Patching Valid CRC32, Only Download Custom Patches On Apply Click

### ISSUE THREAD

**Issue by flagrama** [marcrobledo/RomPatcher.js#35]
This isn't a feature request but more a quick discussion on if one or both parts of the title would be features the patcher would be better off with. I've written both for my own purposes and was wondering if they would be appreciated in a PR before I clean it up to do so.

The changes are as follows:
- (Dis)enabling the Apply Button and the rest of the UI are separated so that it can be toggled separately
- If using the custom patcher the CRC from the currently selected `CUSTOM_PATCHER` object are stored to be compared later.
- If there is no patch but there is a `romFile` and a `patchFileCrc` stored `validateSource` checks equality of the hashes to enable the Apply button, if there are both a `patch` and a `romFile` the Apply button is also enabled if their hashes match. Otherwise it disabled.
- `fetchPatch` has been made a Promise which is required to avoid trying to apply a patch before it is downloaded due the async nature of Javascript.
- If using the custom patcher clicking apply will try to fetch the Patch before trying to apply the Patch, otherwise it will just try to apply the chosen patch file.
- The previous `fetchPatch` usages have been replaced with saving the CRC of the `selectedPatch` and changing the selected patch will invoke `validateSource`.

Only the Apply button being disabled with an invalid CRC affects the normal patcher, and both features would be pretty easy to implement independently if one of them isn't desired.

Is there a reason to apply to a ROM that doesn't match the CRC32? It seems kind of silly to apply a patch in this case as it is usually just more likely to break the ROM. However, if there is a valid reason to do so I can understand.

I think regardless of the above question it would be nice if the custom patches were only downloaded on demand when the user actually wants to use it instead of downloading each on the select box being changed to save on server bandwidth. Is there any reason you wouldn't want this?

**Comment by marcrobledo** [comment]
Yes, it is intended.
In some cases patches that require a valid checksum may work with ROMs that do not validate. People sometimes may have slightly different ROMs (different header, small bits changed here and there, etc) that can still be compatible with those patches. So I decided to just let warn the user the ROM is not valid, but still be able to patch.

As for the custom patcher...
There are also reasons on why patches are downloaded as soon as user selects them:
* if using a patch that requires checksum validation (like BPS, UPS...), patch is downloaded so ROM provided by user can be checked before clicking on Apply (otherwise, user could not know if provided ROM is valid beforehand)
* if `CUSTOM_PATCHER` has a zip file containing multiple patches, it must be downloaded beforehand in order to look for the patches inside. Back when the first custom patcher version compatible was released, you could provide the names and even their CRC32 for every patch inside the zip file. However, it was discarded as it forced author to specify every patch and also it wasn't compatible with [RHDN](https://www.romhacking.net/patch/), which is used when clicking on [Patch Online Now!](https://www.romhacking.net/translations/6402/) and it's impossible to know if zip file contains one or various patches unless you download and unzip it.

**Comment by flagrama** [comment]
Okay, sounds like there are some valid reasons to do both the current way, and if the person hosting the custom patcher wants to make these changes for whatever reason they can just do so since it isn't too difficult.
