### ISSUE TITLE
Hardcoded patcher feature

### ISSUE THREAD

**Issue by romhack** [marcrobledo/RomPatcher.js#7]
Hello!
I was wondering, if it was possible to implement something like an online patcher with patch file already placed on server. Say, for translation group trying to distribute it's patch, it would be cool to have a styled nice page with just one input for ROM file and button 'apply patch'.
I was trying to add additional onload function for getting this patch online. Something like:
```javascript
		var blob = null;
		var xhr = new XMLHttpRequest();
		xhr.open("GET", "./1.ips");
		xhr.responseType = "blob";//force the HTTP response, response-type header to be blob
		xhr.onload = function()
		{
			blob = xhr.response;//xhr.response is now a blob object
			openPatchFile(blob);
		}
		xhr.send();
```
But only succeeded on local file. As soon as I place all the files on server I cannot get proper blob for processing.

**Comment by romhack** [comment]
I have achieved the result with Fetch API:
```javascript
		fetch('./1.ips')
		  .then(res => res.blob()) // Gets the response and returns it as a blob
		  .then(blob => {
			blob.lastModifiedDate = new Date();
			blob.name = "patch";
			openPatchFile(blob);
		})
```
Looks like a hack, of course. I wonder if there is more smooth way to do this.

**Comment by marcrobledo** [comment]
Sorry for the late answer.

This was discussed some time ago with RomHacking.net staff. Yes, it's definitely possible.

There is a new version coming soon with lots of fixes, speed improvements and compatibility with RUP, PPF and xdelta formats. I'll probably work on this after it's released.

**Comment by romhack** [comment]
Great! Looking forward it!

**Comment by marcrobledo** [comment]
Fetch should be the best approach, but it's not compatible with all browsers so an AJAX fallback will be needed.

**Comment by marcrobledo** [comment]
Development is progressing flawlessly!
Both Fetch and XHR work (giving me some headaches with Microsoft Edge though).
![imagen](https://user-images.githubusercontent.com/14358263/52167381-6ba32e00-271a-11e9-95bf-6f494e1ec179.png)

But the best news so far is that since now you can specify patch files, you can also specify crc for source ROMs, so source validation is available even with old formats like IPS :-)

**Comment by marcrobledo** [comment]
That was considered too. But it's not a priority right now.

**Comment by marcrobledo** [comment]
Hardcoded patches and localization have been added in e7d2bccc47844289d30e15ef8dd120e184157db0

However, I'm having problems with Firefox and cache service worker and the site is not showing the latest version, despite files have been comitted correctly. I'll look into it asap since this is giving me headaches in all my projects here in GitHub Pages+Firefox.


Anyway, this is how it works:

You need to define a basic JS  object anywhere in the page or in an additional .js file. This is the object structure:

```
var PREDEFINED_PATCHES=[
			{patch:'./_example/SONICDX.xdelta',name:'Sonic 3D Blast Director\'s Cut v1.1',crc:0x44a2ca44},
			{patch:'./_example/SML2DXv181.ips',name:'Super Mario Land 2 DX v1.81',crc:0xd5ec24e4}
		];
```
Checksum can be added and guarantee validation with any patch (even IPS!) :-D


---


Localization was added in locale.js, adding new languages should be pretty self explanatory.
