### ISSUE TITLE
Ability to create BPS patches?

### ISSUE THREAD

**Issue by NintendoManiac64** [marcrobledo/RomPatcher.js#8]
This patches may support applying IPS, UPS, APS, and BPS patches, but it only supports creating IPS, UPS, and APS patches - support for creating BPS patches is notably absent.

This is kind of unfortunate as I'm trying to find a BPS patch creation utility that actually functions correctly with GameCube games and their 1.35GB size - beat just sits there doing nothing while Floating IPS throws up an error saying "files are too big" even though BPS as a format supposedly has no file size limit...

**Comment by marcrobledo** [comment]
BPS creation was implemented some time ago in the next version I mentioned here https://github.com/marcrobledo/RomPatcher.js/issues/7#issuecomment-456999393

But I can't tell you an approximate date for when will it be ready :-(

**Comment by marcrobledo** [comment]
BPS creation (both normal and quadratic modes) has been added in e7d2bccc47844289d30e15ef8dd120e184157db0

However, I'm having problems with Firefox and cache service worker and the site is not showing the latest version, despite files have been comitted correctly. I'll look into it asap since this is giving me headaches in all my projects here in GitHub Pages+Firefox.
